[build]
  base = "employee-managementUI"
  command = "npm install --force && npm run build"
  publish = "dist/employee-managementUI/browser"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
